package com.keyvault.app.ui

import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.keyvault.app.data.KeyItem
import com.keyvault.app.ui.components.SensitiveClipboard
import com.keyvault.app.ui.theme.glass
import com.keyvault.app.util.KeyGenerator

@Composable
fun GeneratorScreen(model: AppViewModel, onSaved: (KeyItem) -> Unit) {
    var length by remember { mutableIntStateOf(32) }
    var upper by remember { mutableStateOf(true) }
    var lower by remember { mutableStateOf(true) }
    var digits by remember { mutableStateOf(true) }
    var symbols by remember { mutableStateOf(false) }
    var exclude by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf("") }
    val context = LocalContext.current
    val entropy = KeyGenerator.entropyBits(length, upper, lower, digits, symbols, exclude)
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
        Text("密钥生成器", style = MaterialTheme.typography.headlineMedium)
        Text("创建随机、高强度的密钥")
        Column(Modifier.fillMaxWidth().glass().padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text("长度：$length")
            Slider(value = length.toFloat(), onValueChange = { length = it.toInt() }, valueRange = 8f..128f, steps = 119)
            OptionRow("大写字母", upper) { upper = it }
            OptionRow("小写字母", lower) { lower = it }
            OptionRow("数字", digits) { digits = it }
            OptionRow("符号", symbols) { symbols = it }
            OptionRow("排除易混字符", exclude) { exclude = it }
            Text("预计强度：${if (entropy >= 100) "很强" else if (entropy >= 60) "强" else "较弱"} · 约 $entropy 位熵")
            Button(onClick = { generated = KeyGenerator.generate(length, upper = upper, lower = lower, digits = digits, symbols = symbols, excludeAmbiguous = exclude) },
                enabled = upper || lower || digits || symbols, modifier = Modifier.fillMaxWidth()) { Text("生成密钥") }
        }
        if (generated.isNotEmpty()) Column(Modifier.fillMaxWidth().glass().padding(18.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            SecretField(generated, { generated = it }, "生成结果")
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(onClick = { SensitiveClipboard.copy(context, generated); Toast.makeText(context, "已复制，30 秒后清除", Toast.LENGTH_SHORT).show() }) { Text("复制") }
                Button(onClick = {
                    val item = KeyItem(name = "生成的密钥", value = generated)
                    model.saveKey(item)
                    generated = ""
                    onSaved(item)
                }) { Text("保存为密钥") }
            }
        }
    }
}

@Composable
private fun OptionRow(label: String, checked: Boolean, enabled: Boolean = true, onChecked: (Boolean) -> Unit) {
    Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
        Text(label, Modifier.weight(1f)); Switch(checked = checked, onCheckedChange = onChecked, enabled = enabled)
    }
}

@Composable
fun SettingsScreen(
    model: AppViewModel,
    biometricAvailable: Boolean,
    onEnableBiometric: (CharArray, (Boolean) -> Unit) -> Unit,
    onDisableBiometric: () -> Unit,
    onTheme: (String) -> Unit,
    onAccent: (Int) -> Unit,
    themeMode: String,
    accentIndex: Int,
    onExport: () -> Unit,
    onImport: () -> Unit,
) {
    var lockMinutes by remember { mutableIntStateOf(model.settings.lockMinutes) }
    var biometricEnabled by remember { mutableStateOf(model.settings.biometricEnabled) }
    var askPassword by remember { mutableStateOf(false) }
    var masterPassword by remember { mutableStateOf("") }
    var message by remember { mutableStateOf("") }
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp), verticalArrangement = Arrangement.spacedBy(18.dp)) {
        Text("设置", style = MaterialTheme.typography.headlineMedium)
        Column(Modifier.fillMaxWidth().glass().padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text("自动锁定", style = MaterialTheme.typography.titleMedium)
            Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf(0 to "立即", 1 to "1 分钟", 5 to "5 分钟", 15 to "15 分钟").forEach { (minutes, label) ->
                    FilterChip(lockMinutes == minutes, onClick = { lockMinutes = minutes; model.settings.lockMinutes = minutes }, label = { Text(label) })
                }
            }
            OptionRow("生物识别解锁", biometricEnabled, biometricAvailable || biometricEnabled) { enable ->
                if (enable) askPassword = true
                else { onDisableBiometric(); biometricEnabled = false; model.settings.biometricEnabled = false }
            }
            if (!biometricAvailable) Text("设备生物识别不可用；可继续使用主密码。", style = MaterialTheme.typography.bodySmall)
        }
        Column(Modifier.fillMaxWidth().glass().padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text("外观", style = MaterialTheme.typography.titleMedium)
            Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf("dark" to "深色", "light" to "浅色", "system" to "跟随系统").forEach { (mode, label) ->
                    FilterChip(themeMode == mode, onClick = { onTheme(mode) }, label = { Text(label) })
                }
            }
            Text("强调色")
            Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf("紫", "青", "粉", "绿").forEachIndexed { index, label ->
                    FilterChip(accentIndex == index, onClick = { onAccent(index) }, label = { Text(label) })
                }
            }
        }
        Column(Modifier.fillMaxWidth().glass().padding(18.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("备份", style = MaterialTheme.typography.titleMedium)
            Text("导出文件仍由主密码加密。导入时需要输入备份文件的主密码。")
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(onClick = onExport) { Text("导出 .kvault") }
                OutlinedButton(onClick = onImport) { Text("导入") }
            }
        }
        Column(Modifier.fillMaxWidth().glass().padding(18.dp)) {
            Text("关于 KeyVault", style = MaterialTheme.typography.titleMedium)
            Text("版本 2.0 · 本地加密密钥与记事本")
        }
        if (message.isNotBlank()) Text(message, color = MaterialTheme.colorScheme.primary)
    }
    if (askPassword) AlertDialog(
        onDismissRequest = { askPassword = false; masterPassword = "" },
        title = { Text("启用生物识别") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("请先验证当前主密码。通过后由系统进行生物识别。")
                SecretField(masterPassword, { masterPassword = it }, "当前主密码")
            }
        },
        confirmButton = { TextButton(onClick = {
            val verify = masterPassword.toCharArray()
            val enroll = masterPassword.toCharArray()
            masterPassword = ""
            askPassword = false
            model.verifyPassword(verify) { verified ->
                if (!verified) { enroll.fill('\u0000'); message = "主密码不正确" }
                else if (!biometricAvailable) { enroll.fill('\u0000'); message = "设备生物识别不可用" }
                else onEnableBiometric(enroll) { success ->
                    biometricEnabled = success
                    model.settings.biometricEnabled = success
                    message = if (success) "生物识别已启用" else "生物识别设置失败，请使用主密码"
                }
            }
        }, enabled = masterPassword.isNotEmpty()) { Text("继续") } },
        dismissButton = { TextButton(onClick = { askPassword = false; masterPassword = "" }) { Text("取消") } },
    )
}
